package org.vision.wechat.persistence.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_check_record
 */
@Data
public class CheckRecordPO implements Serializable {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.check_record_id
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Integer checkRecordId;

    /**
     * Database Column Remarks:
     *   微信用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.wx_user_id
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Integer wxUserId;

    /**
     * Database Column Remarks:
     *   设备id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.device_id
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Integer deviceId;

    /**
     * Database Column Remarks:
     *   设备类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.device_type
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private String deviceType;

    /**
     * Database Column Remarks:
     *   检测日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.check_date
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Date checkDate;

    /**
     * Database Column Remarks:
     *   数据类型：number-数字，picture-图像，图像只有一幅，图像类型时，左右眼标识忽略
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.data_type
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private String dataType;

    /**
     * Database Column Remarks:
     *   左右眼：OD-左眼，OS-右眼
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.eye_type
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private String eyeType;

    /**
     * Database Column Remarks:
     *   瞳孔大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.pupil
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Double pupil;

    /**
     * Database Column Remarks:
     *   CYL-等效球面度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.se1
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Double se1;

    /**
     * Database Column Remarks:
     *   CYL-球面度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.ds1
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Double ds1;

    /**
     * Database Column Remarks:
     *   CYL-柱面度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.dc1
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Double dc1;

    /**
     * Database Column Remarks:
     *   CYL-柱面轴位角
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.axis1
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Integer axis1;

    /**
     * Database Column Remarks:
     *   CYL+等效球面度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.se2
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Double se2;

    /**
     * Database Column Remarks:
     *   CYL+球面度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.ds2
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Double ds2;

    /**
     * Database Column Remarks:
     *   CYL+柱面度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.dc2
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Double dc2;

    /**
     * Database Column Remarks:
     *   CYL+柱面轴位角
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.axis2
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Integer axis2;

    /**
     * Database Column Remarks:
     *   瞳距
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.pd
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Integer pd;

    /**
     * Database Column Remarks:
     *   眼压
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.mm_hg
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Double mmHg;

    /**
     * Database Column Remarks:
     *   水平固视
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.gaze_horizontal
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Integer gazeHorizontal;

    /**
     * Database Column Remarks:
     *   垂直固视
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.gazev_vertical
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Integer gazevVertical;

    /**
     * Database Column Remarks:
     *   校验码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.check_code
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private String checkCode;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.remark
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.create_user_id
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Integer createUserId;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.create_user_name
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private String createUserName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.create_create
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Date createCreate;

    /**
     * Database Column Remarks:
     *   修改人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.modified_user_id
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Integer modifiedUserId;

    /**
     * Database Column Remarks:
     *   修改人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.modified_user_name
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private String modifiedUserName;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.modified_date
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Date modifiedDate;

    /**
     * Database Column Remarks:
     *   数据有效性：1=有效；0=无效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check_record.valid
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private Boolean valid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_check_record
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    private static final long serialVersionUID = 1L;
}