package org.vision.wechat.persistence.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table vision_client
 */
@Data
public class VisionClientPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.id
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private String id;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.name
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private String name;

    /**
     * Database Column Remarks:
     *   -1: 年龄保密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.age
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.birthday
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.phone_number
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private String phoneNumber;

    /**
     * Database Column Remarks:
     *   省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.province
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private String province;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.city
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private String city;

    /**
     * Database Column Remarks:
     *   区县
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.county
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private String county;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.detail_address
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private String detailAddress;

    /**
     * Database Column Remarks:
     *   0:未知,1:男性,2:女性
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.gender
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private Boolean gender;

    /**
     * Database Column Remarks:
     *   身份证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vision_client.id_number
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vision_client
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    private static final long serialVersionUID = 1L;
}