package org.vision.wechat.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.vision.wechat.persistence.model.SysDictionaryPO;
import org.vision.wechat.persistence.model.SysDictionaryPOExample;

@Mapper
public interface SysDictionaryPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    long countByExample(SysDictionaryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int deleteByExample(SysDictionaryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int deleteByPrimaryKey(Integer sysDictionaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int insert(SysDictionaryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int insertSelective(SysDictionaryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    List<SysDictionaryPO> selectByExample(SysDictionaryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    SysDictionaryPO selectByPrimaryKey(Integer sysDictionaryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysDictionaryPO record, @Param("example") SysDictionaryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int updateByExample(@Param("record") SysDictionaryPO record, @Param("example") SysDictionaryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int updateByPrimaryKeySelective(SysDictionaryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int updateByPrimaryKey(SysDictionaryPO record);
}