package org.vision.wechat.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.vision.wechat.model.CheckRecordGetListBO;
import org.vision.wechat.persistence.model.VisionCheckReportPO;
import org.vision.wechat.persistence.model.VisionCheckReportPOExample;

@Mapper
public interface VisionCheckReportPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    long countByExample(VisionCheckReportPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    int deleteByExample(VisionCheckReportPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    int insert(VisionCheckReportPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    int insertSelective(VisionCheckReportPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    List<VisionCheckReportPO> selectByExample(VisionCheckReportPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    VisionCheckReportPO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") VisionCheckReportPO record, @Param("example") VisionCheckReportPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    int updateByExample(@Param("record") VisionCheckReportPO record, @Param("example") VisionCheckReportPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    int updateByPrimaryKeySelective(VisionCheckReportPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vision_check_report
     *
     * @mbg.generated Mon Feb 18 15:54:25 CST 2019
     */
    int updateByPrimaryKey(VisionCheckReportPO record);

    List<CheckRecordGetListBO> list(CheckRecordGetListBO bo);
}