package org.vision.wechat.persistence.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.vision.wechat.persistence.model.WxUserPO;
import org.vision.wechat.persistence.model.WxUserPOExample;

@Mapper
public interface WxUserPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    long countByExample(WxUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int deleteByExample(WxUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int deleteByPrimaryKey(Integer wxUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int insert(WxUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int insertSelective(WxUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    List<WxUserPO> selectByExample(WxUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    WxUserPO selectByPrimaryKey(Integer wxUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") WxUserPO record, @Param("example") WxUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int updateByExample(@Param("record") WxUserPO record, @Param("example") WxUserPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int updateByPrimaryKeySelective(WxUserPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wx_user
     *
     * @mbg.generated Mon Jan 21 10:15:48 CST 2019
     */
    int updateByPrimaryKey(WxUserPO record);
}